# Generated by Django 5.0.4 on 2024-05-31 11:53

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0006_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
